spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: {POSTGRES_USER}
    password: {POSTGRES_PASSWORD}


#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5444/achive2-api
#    username: admin
#    password: admin
server:
  error:
    include-message: always
    include-binding-errors: always
