apiVersion: apps/v1
kind: Deployment
metadata:
  name: achieve2
  labels:
    app: achieve2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: achieve2
  template:
    metadata:
      labels:
        app: achieve2
    spec:
      containers:
        - name: achieve2
          image: pelease/achieve2:9.0.0
          ports:
            - containerPort: 8080
#          env:
#            - name: DB_HOST
#              value: 172.16.2.34
#            - name: DB_NAME
#                value: achieve2-api
#            - name: POSTGRES_USER
#              value: postgres
#            - name: POSTGRES_PASSWORD
#              value: postgres

          env:
            - name: DB_HOST
              value: 172.16.2.34
            - name: DB_PORT
              value: "32320"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
      nodeName: node-16